language: go
matrix:
  include:
    - go: 1.8.x
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.linuxbrew/
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - glide
    - build-essential
    - jq
install:
  - make travis
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)

env:
  global:
  - PROTOBUF_VER="3.3.0"
  - PATH=$HOME/protobuf/bin:$PATH
