language: go
dist: xenial
sudo: required
services:
  - docker
before_install:
  - cd ${TRAVIS_BUILD_DIR}/dockerfiles/base
  - make docker_build_cpu
  - make docker_build_gpu
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make docker_push_cpu
  - make docker_push_gpu
